export interface Faq { id: string; question: string; answer: string; category: string; sort_order: number }

export const fallbackFaqs: Faq[] = [
  { id: 'faq-01', question: 'How do I choose the right Aurvelia serum for my skin?', answer: 'Begin with your primary concern — hydration, brightening or anti-ageing. Our Vitamin C Radiance Serum targets dullness and pigmentation; the Hydrating Serum supports moisture retention. Check product descriptions for skin-suitable types or contact our skin advisors.', category: 'Products', sort_order: 1 },
  { id: 'faq-02', question: 'Are Aurvelia products cruelty-free?', answer: 'Yes. Aurvelia does not test on animals and sources ingredients from ethical suppliers. We continually review our supply chain to uphold cruelty-free commitments.', category: 'Ethos', sort_order: 1 },
  { id: 'faq-03', question: 'Do you offer international shipping?', answer: 'We ship internationally from our fulfilment centers. Shipping costs and delivery times vary by destination — add your address at checkout for an accurate estimate.', category: 'Shipping', sort_order: 1 },
  { id: 'faq-04', question: 'What is your returns policy?', answer: 'We accept returns within 30 days of delivery for unopened and unused items. Opened products are eligible for exchange or store credit in case of damage. Contact support for assistance.', category: 'Orders', sort_order: 1 },
  { id: 'faq-05', question: 'How should I layer Aurvelia skincare?', answer: 'Apply from lightest to heaviest: cleanser → toner → serum → moisturizer → sunscreen in the morning. At night, you can include richer treatments and masks as needed.', category: 'Usage', sort_order: 1 },
  { id: 'faq-06', question: 'Are Aurvelia formulas safe for sensitive skin?', answer: 'Many of our formulas are designed for sensitive skin; look for products labelled soothing or for sensitive types. If you have severe sensitivities, patch-test or consult your dermatologist.', category: 'Products', sort_order: 2 },
  { id: 'faq-07', question: 'Do Aurvelia products contain fragrances?', answer: 'Some Aurvelia products have a light natural fragrance from botanical extracts. We avoid unnecessary synthetic fragrances in our core ranges.', category: 'Ingredients', sort_order: 1 },
  { id: 'faq-08', question: 'How long until I see results?', answer: 'Visible improvements vary by product and concern; many customers notice hydration and texture improvements within 1–2 weeks, with more significant changes (tone, lines) appearing over 4–8 weeks with consistent use.', category: 'Expectations', sort_order: 1 },
  { id: 'faq-09', question: 'Can I use Aurvelia products with retinoids?', answer: 'Yes, though we recommend introducing active treatments gradually. Pair gentle hydrating serums and barrier-supporting moisturizers when using retinoids to reduce irritation.', category: 'Usage', sort_order: 2 },
  { id: 'faq-10', question: 'How should I store my skincare products?', answer: 'Store in a cool, dry place away from direct sunlight. Some active formulations (like vitamin C) benefit from cool storage to preserve potency.', category: 'Care', sort_order: 1 },
  { id: 'faq-11', question: 'Do you offer samples?', answer: 'We occasionally include samples with orders and during promotional events. Sign up for our newsletter for early access and sample opportunities.', category: 'Orders', sort_order: 2 },
  { id: 'faq-12', question: 'How do I contact customer support?', answer: 'Visit the contact page for our support form or email our customer care team; we typically reply within 48 hours on business days.', category: 'Support', sort_order: 1 },
  { id: 'faq-13', question: 'Are Aurvelia products safe during pregnancy?', answer: 'Some actives are not recommended during pregnancy. Check ingredient lists and consult your physician before introducing new active treatments.', category: 'Safety', sort_order: 1 },
  { id: 'faq-14', question: 'Can I layer multiple serums?', answer: 'Yes. Apply thinner, water-based serums first and seal with an oil or moisturizer. Avoid combining incompatible actives without guidance.', category: 'Usage', sort_order: 3 },
  { id: 'faq-15', question: 'What payment methods do you accept?', answer: 'We accept major credit cards, PayPal and regional payment options where available. Payment methods are shown at checkout.', category: 'Orders', sort_order: 3 },
];

export default fallbackFaqs;
