import serum from "@/assets/products/serum.jpg";
import cleanser from "@/assets/products/cleanser.jpg";
import moisturizer from "@/assets/products/moisturizer.jpg";
import sunscreen from "@/assets/products/sunscreen.jpg";
import toner from "@/assets/products/toner.jpg";
import mask from "@/assets/products/mask.jpg";
import lip from "@/assets/products/lip.jpg";
import body from "@/assets/products/body.jpg";
import type { Product } from "@/lib/products";

export const fallbackProducts: Product[] = [
  // Serums (serum.jpg)
  {
    id: "serum-glow-01",
    sku: "AURV-SRM-GLO-01",
    name: "Glow Serum",
    slug: "glow-serum",
    category: "serum",
    brand: "Aurvelia",
    description: "Lightweight radiance-boosting serum that restores glow and evens tone.",
    price: 699,
    sale_price: null,
    stock: 50,
    ingredients: ["Vitamin C", "Hyaluronic Acid", "Peptides"],
    benefits: ["Brightening", "Hydration", "Even tone"],
    skin_types: ["All"],
    skin_concerns: ["Dullness", "Texture"],
    how_to_use: "Apply 2–3 drops to cleansed skin each morning before moisturizer.",
    images: [serum],
    featured: true,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.8,
    review_count: 320,
  },
  {
    id: "serum-vitc-01",
    sku: "AURV-SRM-VITC-01",
    name: "Vitamin C Radiance Serum",
    slug: "vitamin-c-radiance-serum",
    category: "serum",
    brand: "Aurvelia",
    description: "Stabilized vitamin C serum to reduce pigmentation and boost luminosity.",
    price: 649,
    sale_price: null,
    stock: 40,
    ingredients: ["Ascorbic Acid", "Ferulic Acid", "Vitamin E"],
    benefits: ["Brightening", "Antioxidant protection"],
    skin_types: ["Normal", "Dry", "Combination"],
    skin_concerns: ["Pigmentation", "Dullness"],
    how_to_use: "Use in the morning under sunscreen; 2–3 drops over face and neck.",
    images: [serum],
    featured: true,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.7,
    review_count: 210,
  },
  {
    id: "serum-niacin-01",
    sku: "AURV-SRM-NIA-01",
    name: "Niacinamide Repair Serum",
    slug: "niacinamide-repair-serum",
    category: "serum",
    brand: "Aurvelia",
    description: "Concentrated niacinamide formula to strengthen barrier and refine pores.",
    price: 599,
    sale_price: null,
    stock: 45,
    ingredients: ["Niacinamide", "Zinc PCA", "Panthenol"],
    benefits: ["Pore refinement", "Barrier support", "Oil control"],
    skin_types: ["Oily", "Combination"],
    skin_concerns: ["Pores", "Uneven texture"],
    how_to_use: "Apply once or twice daily before moisturizer.",
    images: [serum],
    featured: false,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.6,
    review_count: 154,
  },
  {
    id: "serum-hydra-01",
    sku: "AURV-SRM-HYD-01",
    name: "Hydration Boost Serum",
    slug: "hydration-boost-serum",
    category: "serum",
    brand: "Aurvelia",
    description: "Hyaluronic-rich serum for plump, dewy skin and long-lasting moisture.",
    price: 549,
    sale_price: null,
    stock: 60,
    ingredients: ["Hyaluronic Acid", "Glycerin", "Sodium PCA"],
    benefits: ["Deep hydration", "Plumping"],
    skin_types: ["All"],
    skin_concerns: ["Dehydration"],
    how_to_use: "Apply to damp skin for optimal hydration, morning and night.",
    images: [serum],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.5,
    review_count: 98,
  },
  {
    id: "serum-bright-01",
    sku: "AURV-SRM-BRT-01",
    name: "Brightening Complex Serum",
    slug: "brightening-complex-serum",
    category: "serum",
    brand: "Aurvelia",
    description: "Multi-action brightening serum with gentle acids and botanicals for glow.",
    price: 699,
    sale_price: null,
    stock: 30,
    ingredients: ["Lactic Acid", "Vitamin C", "Botanical extracts"],
    benefits: ["Radiance", "Exfoliation", "Tone correction"],
    skin_types: ["All"],
    skin_concerns: ["Dullness", "Uneven tone"],
    how_to_use: "Use 2–3 times weekly at night; follow with moisturizer.",
    images: [serum],
    featured: true,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.6,
    review_count: 72,
  },

  // Cleansers (cleanser.jpg)
  {
    id: "cleanser-silk-01",
    sku: "AURV-CLN-SLK-01",
    name: "Silk Cleanser",
    slug: "silk-cleanser",
    category: "cleanser",
    brand: "Aurvelia",
    description: "Creamy silk-texture cleanser that lifts impurities without stripping.",
    price: 399,
    sale_price: null,
    stock: 80,
    ingredients: ["Squalane", "Glycerin", "Oat Extract"],
    benefits: ["Gentle cleansing", "Hydration"],
    skin_types: ["Dry", "Sensitive"],
    skin_concerns: ["Dryness"],
    how_to_use: "Massage onto damp skin, rinse thoroughly.",
    images: [cleanser],
    featured: false,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.7,
    review_count: 190,
  },
  {
    id: "cleanser-gentle-01",
    sku: "AURV-CLN-GEN-01",
    name: "Gentle Daily Cleanser",
    slug: "gentle-daily-cleanser",
    category: "cleanser",
    brand: "Aurvelia",
    description: "Light foaming cleanser for everyday freshness without tightness.",
    price: 349,
    sale_price: null,
    stock: 90,
    ingredients: ["Glycerin", "Betaine", "Aloe"],
    benefits: ["Daily cleansing", "Soothing"],
    skin_types: ["All"],
    skin_concerns: ["Sensitivity"],
    how_to_use: "Use morning and evening on wet skin, rinse off.",
    images: [cleanser],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.5,
    review_count: 120,
  },
  {
    id: "cleanser-deep-01",
    sku: "AURV-CLN-DP-01",
    name: "Deep Pore Cleanser",
    slug: "deep-pore-cleanser",
    category: "cleanser",
    brand: "Aurvelia",
    description: "Clarifying cleanser with gentle exfoliants to clear congested pores.",
    price: 449,
    sale_price: null,
    stock: 55,
    ingredients: ["Salicylic Acid", "Kaolin", "Charcoal"],
    benefits: ["Deep cleanse", "Exfoliation"],
    skin_types: ["Oily", "Combination"],
    skin_concerns: ["Clogged pores", "Oiliness"],
    how_to_use: "Use 2–3 times weekly; lather and rinse.",
    images: [cleanser],
    featured: false,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.4,
    review_count: 88,
  },
  {
    id: "cleanser-foam-01",
    sku: "AURV-CLN-FM-01",
    name: "Hydrating Foam Cleanser",
    slug: "hydrating-foam-cleanser",
    category: "cleanser",
    brand: "Aurvelia",
    description: "Airy foam cleanser that removes makeup traces while replenishing moisture.",
    price: 499,
    sale_price: null,
    stock: 60,
    ingredients: ["Hyaluronic Acid", "Coconut-derived cleansers"],
    benefits: ["Makeup removal", "Hydration"],
    skin_types: ["All"],
    skin_concerns: ["Dryness"],
    how_to_use: "Foam on palms, massage over face, rinse.",
    images: [cleanser],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.5,
    review_count: 66,
  },
  {
    id: "cleanser-green-01",
    sku: "AURV-CLN-GT-01",
    name: "Green Tea Purifying Cleanser",
    slug: "green-tea-purifying-cleanser",
    category: "cleanser",
    brand: "Aurvelia",
    description: "Refreshing cleanser with green tea extract to purify and soothe.",
    price: 449,
    sale_price: null,
    stock: 70,
    ingredients: ["Green Tea", "Glycerin", "Allantoin"],
    benefits: ["Purifying", "Antioxidant"],
    skin_types: ["All"],
    skin_concerns: ["Pollution", "Dullness"],
    how_to_use: "Massage onto damp skin and rinse thoroughly.",
    images: [cleanser],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.4,
    review_count: 54,
  },

  // Moisturizers (moisturizer.jpg)
  {
    id: "moist-hydra-01",
    sku: "AURV-MST-HYD-01",
    name: "Hydra Cream",
    slug: "hydra-cream",
    category: "moisturizer",
    brand: "Aurvelia",
    description: "Rich moisturizing cream that locks in hydration for the day.",
    price: 599,
    sale_price: null,
    stock: 65,
    ingredients: ["Glycerin", "Ceramides", "Squalane"],
    benefits: ["Long-lasting hydration", "Barrier repair"],
    skin_types: ["Dry", "Normal"],
    skin_concerns: ["Dehydration"],
    how_to_use: "Apply morning and evening to face and neck.",
    images: [moisturizer],
    featured: true,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.7,
    review_count: 230,
  },
  {
    id: "moist-barrier-01",
    sku: "AURV-MST-BAR-01",
    name: "Barrier Repair Moisturizer",
    slug: "barrier-repair-moisturizer",
    category: "moisturizer",
    brand: "Aurvelia",
    description: "Ceramide-rich moisturizer to restore and strengthen the skin barrier.",
    price: 649,
    sale_price: null,
    stock: 40,
    ingredients: ["Ceramides", "Niacinamide", "Squalane"],
    benefits: ["Barrier support", "Soothing"],
    skin_types: ["Sensitive", "Dry"],
    skin_concerns: ["Sensitivity", "Barrier damage"],
    how_to_use: "Use morning and night after treatment serums.",
    images: [moisturizer],
    featured: true,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.8,
    review_count: 142,
  },
  {
    id: "moist-daily-01",
    sku: "AURV-MST-DLY-01",
    name: "Daily Hydration Cream",
    slug: "daily-hydration-cream",
    category: "moisturizer",
    brand: "Aurvelia",
    description: "Light everyday cream for balanced hydration and comfort.",
    price: 549,
    sale_price: null,
    stock: 75,
    ingredients: ["Squalane", "Glycerin", "Panthenol"],
    benefits: ["Hydration", "Comfort"],
    skin_types: ["All"],
    skin_concerns: ["Dryness"],
    how_to_use: "Apply as the last step in your routine morning and night.",
    images: [moisturizer],
    featured: false,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.6,
    review_count: 178,
  },
  {
    id: "moist-ceramide-01",
    sku: "AURV-MST-CER-01",
    name: "Ceramide Moisturizer",
    slug: "ceramide-moisturizer",
    category: "moisturizer",
    brand: "Aurvelia",
    description: "Concentrated ceramide formula to restore moisture and resilience.",
    price: 699,
    sale_price: null,
    stock: 35,
    ingredients: ["Ceramides", "Cholesterol", "Fatty acids"],
    benefits: ["Barrier repair", "Deep nourishment"],
    skin_types: ["Dry", "Sensitive"],
    skin_concerns: ["Barrier damage"],
    how_to_use: "Apply twice daily after serums.",
    images: [moisturizer],
    featured: true,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.7,
    review_count: 99,
  },
  {
    id: "moist-gel-01",
    sku: "AURV-MST-GEL-01",
    name: "Lightweight Gel Moisturizer",
    slug: "lightweight-gel-moisturizer",
    category: "moisturizer",
    brand: "Aurvelia",
    description: "Oil-free gel for quick-absorbing hydration and a matte finish.",
    price: 499,
    sale_price: null,
    stock: 90,
    ingredients: ["Hyaluronic Acid", "Glycerin", "Niacinamide"],
    benefits: ["Hydration", "Lightweight finish"],
    skin_types: ["Oily", "Combination"],
    skin_concerns: ["Shine", "Dehydration"],
    how_to_use: "Apply a pea-sized amount to face after serums.",
    images: [moisturizer],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.5,
    review_count: 77,
  },

  // Sunscreens (sunscreen.jpg)
  {
    id: "spf-shield-01",
    sku: "AURV-SPF-SLD-01",
    name: "Sun Shield SPF 50",
    slug: "sun-shield-spf-50",
    category: "sunscreen",
    brand: "Aurvelia",
    description: "Broad-spectrum sunscreen with a lightweight, protective finish.",
    price: 549,
    sale_price: null,
    stock: 70,
    ingredients: ["Zinc Oxide", "Vitamin E"],
    benefits: ["UV protection", "Antioxidant"],
    skin_types: ["All"],
    skin_concerns: ["Sun protection"],
    how_to_use: "Apply generously 15 minutes before sun exposure and reapply every 2 hours.",
    images: [sunscreen],
    featured: false,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.6,
    review_count: 134,
  },
  {
    id: "spf-matte-01",
    sku: "AURV-SPF-MAT-01",
    name: "Matte Defense SPF 50",
    slug: "matte-defense-spf-50",
    category: "sunscreen",
    brand: "Aurvelia",
    description: "Non-greasy matte sunscreen ideal for oily and combination skin.",
    price: 599,
    sale_price: null,
    stock: 55,
    ingredients: ["Chemical + mineral blend", "Silica"],
    benefits: ["Matte finish", "High protection"],
    skin_types: ["Oily", "Combination"],
    skin_concerns: ["Shine", "UV protection"],
    how_to_use: "Apply as last step in morning routine; reapply as needed.",
    images: [sunscreen],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.5,
    review_count: 88,
  },
  {
    id: "spf-daily-01",
    sku: "AURV-SPF-DLY-01",
    name: "Daily Protection SPF 40",
    slug: "daily-protection-spf-40",
    category: "sunscreen",
    brand: "Aurvelia",
    description: "Everyday sunscreen with lightweight feel and hydration boost.",
    price: 499,
    sale_price: null,
    stock: 85,
    ingredients: ["Chemical filters", "Glycerin"],
    benefits: ["Daily protection", "Hydration"],
    skin_types: ["All"],
    skin_concerns: ["Sun protection"],
    how_to_use: "Apply liberally before sun exposure.",
    images: [sunscreen],
    featured: false,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.4,
    review_count: 96,
  },
  {
    id: "spf-ultra-01",
    sku: "AURV-SPF-ULTR-01",
    name: "Ultra Shield SPF 50+",
    slug: "ultra-shield-spf-50-plus",
    category: "sunscreen",
    brand: "Aurvelia",
    description: "High-performance sunscreen for extended outdoor protection.",
    price: 649,
    sale_price: null,
    stock: 40,
    ingredients: ["Zinc Oxide", "Titanium Dioxide"],
    benefits: ["High protection", "Water resistant"],
    skin_types: ["All"],
    skin_concerns: ["Sun exposure"],
    how_to_use: "Apply generously; reapply after swimming or heavy sweating.",
    images: [sunscreen],
    featured: true,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.6,
    review_count: 58,
  },
  {
    id: "spf-invisible-01",
    sku: "AURV-SPF-INV-01",
    name: "Invisible Finish Sunscreen",
    slug: "invisible-finish-sunscreen",
    category: "sunscreen",
    brand: "Aurvelia",
    description: "Sheer, invisible sunscreen that layers under makeup cleanly.",
    price: 699,
    sale_price: null,
    stock: 30,
    ingredients: ["Advanced filters", "Silicone-free esters"],
    benefits: ["Invisible finish", "Non-greasy"],
    skin_types: ["All"],
    skin_concerns: ["Makeup compatibility"],
    how_to_use: "Apply as final morning step; reapply every 2 hours outdoors.",
    images: [sunscreen],
    featured: true,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.7,
    review_count: 102,
  },

  // Toners (toner.jpg)
  {
    id: "toner-radiant-01",
    sku: "AURV-TNR-RAD-01",
    name: "Radiant Toner",
    slug: "radiant-toner",
    category: "toner",
    brand: "Aurvelia",
    description: "Light exfoliating toner that refines texture and brightens skin.",
    price: 449,
    sale_price: null,
    stock: 60,
    ingredients: ["Lactic Acid", "Niacinamide"],
    benefits: ["Exfoliation", "Tone refinement"],
    skin_types: ["All"],
    skin_concerns: ["Texture", "Dullness"],
    how_to_use: "Apply after cleansing with a cotton pad or pat in.",
    images: [toner],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.5,
    review_count: 74,
  },
  {
    id: "toner-rose-01",
    sku: "AURV-TNR-ROS-01",
    name: "Rose Water Toner",
    slug: "rose-water-toner",
    category: "toner",
    brand: "Aurvelia",
    description: "Soothing rose water mist to calm and hydrate skin.",
    price: 399,
    sale_price: null,
    stock: 90,
    ingredients: ["Rose Distillate", "Glycerin"],
    benefits: ["Soothing", "Hydration"],
    skin_types: ["Sensitive", "All"],
    skin_concerns: ["Redness"],
    how_to_use: "Spritz onto face after cleansing or over makeup for a refresh.",
    images: [toner],
    featured: false,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.6,
    review_count: 120,
  },
  {
    id: "toner-mist-01",
    sku: "AURV-TNR-MST-01",
    name: "Hydrating Toner Mist",
    slug: "hydrating-toner-mist",
    category: "toner",
    brand: "Aurvelia",
    description: "Fine mist toner that adds an instant hydration boost throughout the day.",
    price: 499,
    sale_price: null,
    stock: 70,
    ingredients: ["Hyaluronic Acid", "Glycerin"],
    benefits: ["Hydration", "Refresh"],
    skin_types: ["All"],
    skin_concerns: ["Dehydration"],
    how_to_use: "Spray over face as needed; ideal over makeup or post-exercise.",
    images: [toner],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.5,
    review_count: 46,
  },
  {
    id: "toner-balance-01",
    sku: "AURV-TNR-BAL-01",
    name: "Balancing Toner",
    slug: "balancing-toner",
    category: "toner",
    brand: "Aurvelia",
    description: "PH-balancing toner to prepare skin for active treatments.",
    price: 549,
    sale_price: null,
    stock: 50,
    ingredients: ["AHA blend", "Allantoin"],
    benefits: ["PH balance", "Enhanced absorption"],
    skin_types: ["All"],
    skin_concerns: ["Sensitivity", "Treatment prep"],
    how_to_use: "Use after cleansing to prime skin for serums.",
    images: [toner],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.6,
    review_count: 58,
  },
  {
    id: "toner-pore-01",
    sku: "AURV-TNR-POR-01",
    name: "Pore Refining Toner",
    slug: "pore-refining-toner",
    category: "toner",
    brand: "Aurvelia",
    description: "Targeted toner to refine pores and smooth skin texture.",
    price: 599,
    sale_price: null,
    stock: 45,
    ingredients: ["BHA", "Niacinamide"],
    benefits: ["Pore control", "Smoother texture"],
    skin_types: ["Oily", "Combination"],
    skin_concerns: ["Pores", "Texture"],
    how_to_use: "Apply 2–3 times weekly; avoid overuse with other acids.",
    images: [toner],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.4,
    review_count: 39,
  },

  // Masks (mask.jpg)
  {
    id: "mask-clay-01",
    sku: "AURV-MSK-CLY-01",
    name: "Clay Renewal Mask",
    slug: "clay-renewal-mask",
    category: "mask",
    brand: "Aurvelia",
    description: "Detoxifying clay mask to renew skin and refine texture.",
    price: 499,
    sale_price: null,
    stock: 40,
    ingredients: ["Kaolin", "Bentonite"],
    benefits: ["Detoxify", "Refine pores"],
    skin_types: ["Oily", "Combination"],
    skin_concerns: ["Pores", "Congestion"],
    how_to_use: "Apply a thin layer for 10–12 minutes, then rinse.",
    images: [mask],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.4,
    review_count: 48,
  },
  {
    id: "mask-char-01",
    sku: "AURV-MSK-CHR-01",
    name: "Detox Charcoal Mask",
    slug: "detox-charcoal-mask",
    category: "mask",
    brand: "Aurvelia",
    description: "Charcoal detox mask to draw out impurities and brighten complexion.",
    price: 549,
    sale_price: null,
    stock: 35,
    ingredients: ["Activated Charcoal", "Kaolin"],
    benefits: ["Purify", "Brighten"],
    skin_types: ["Oily", "Combination"],
    skin_concerns: ["Clogged pores"],
    how_to_use: "Use weekly for deep cleansing; rinse thoroughly.",
    images: [mask],
    featured: false,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.5,
    review_count: 64,
  },
  {
    id: "mask-bright-01",
    sku: "AURV-MSK-BRT-01",
    name: "Brightening Glow Mask",
    slug: "brightening-glow-mask",
    category: "mask",
    brand: "Aurvelia",
    description: "Illuminating mask to enhance radiance and reveal a fresh glow.",
    price: 599,
    sale_price: null,
    stock: 28,
    ingredients: ["Vitamin C", "Kaolin"],
    benefits: ["Glow", "Exfoliation"],
    skin_types: ["All"],
    skin_concerns: ["Dullness"],
    how_to_use: "Apply once or twice weekly for 10 minutes.",
    images: [mask],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.6,
    review_count: 51,
  },
  {
    id: "mask-overnight-01",
    sku: "AURV-MSK-OVR-01",
    name: "Overnight Recovery Mask",
    slug: "overnight-recovery-mask",
    category: "mask",
    brand: "Aurvelia",
    description: "Overnight restorative mask that soothes and repairs while you sleep.",
    price: 649,
    sale_price: null,
    stock: 22,
    ingredients: ["Ceramides", "Peptides", "Squalane"],
    benefits: ["Repair", "Hydration"],
    skin_types: ["Dry", "Sensitive"],
    skin_concerns: ["Dehydration", "Barrier damage"],
    how_to_use: "Apply a thin layer before bed and leave on overnight.",
    images: [mask],
    featured: true,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.7,
    review_count: 33,
  },
  {
    id: "mask-hydra-01",
    sku: "AURV-MSK-HYD-01",
    name: "Hydration Therapy Mask",
    slug: "hydration-therapy-mask",
    category: "mask",
    brand: "Aurvelia",
    description: "Intensive hydrating mask to replenish moisture and soothe skin.",
    price: 699,
    sale_price: null,
    stock: 18,
    ingredients: ["Hyaluronic Acid", "Aloe Vera"],
    benefits: ["Deep hydration", "Soothing"],
    skin_types: ["Dry", "Sensitive"],
    skin_concerns: ["Dehydration"],
    how_to_use: "Apply once weekly or as needed for intense hydration.",
    images: [mask],
    featured: true,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.8,
    review_count: 29,
  },

  // Lip Care (lip.jpg)
  {
    id: "lip-velvet-01",
    sku: "AURV-LIP-VEL-01",
    name: "Velvet Lip Repair",
    slug: "velvet-lip-repair",
    category: "lip",
    brand: "Aurvelia",
    description: "Nourishing lip balm for instant comfort and smoothness.",
    price: 299,
    sale_price: null,
    stock: 150,
    ingredients: ["Shea Butter", "Squalane"],
    benefits: ["Repair", "Hydration"],
    skin_types: ["All"],
    skin_concerns: ["Dryness"],
    how_to_use: "Apply liberally as needed throughout the day.",
    images: [lip],
    featured: false,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.6,
    review_count: 210,
  },
  {
    id: "lip-overnight-01",
    sku: "AURV-LIP-OVR-01",
    name: "Overnight Lip Mask",
    slug: "overnight-lip-mask",
    category: "lip",
    brand: "Aurvelia",
    description: "Overnight intensive lip mask to restore softness by morning.",
    price: 349,
    sale_price: null,
    stock: 120,
    ingredients: ["Jojoba Oil", "Shea Butter"],
    benefits: ["Overnight repair", "Softening"],
    skin_types: ["All"],
    skin_concerns: ["Cracked lips"],
    how_to_use: "Apply a generous layer before sleep.",
    images: [lip],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.5,
    review_count: 82,
  },
  {
    id: "lip-shea-01",
    sku: "AURV-LIP-SHEA-01",
    name: "Shea Butter Lip Balm",
    slug: "shea-butter-lip-balm",
    category: "lip",
    brand: "Aurvelia",
    description: "Classic shea butter balm for everyday protection and nourishment.",
    price: 399,
    sale_price: null,
    stock: 140,
    ingredients: ["Shea Butter", "Vitamin E"],
    benefits: ["Protection", "Softness"],
    skin_types: ["All"],
    skin_concerns: ["Dryness"],
    how_to_use: "Apply as needed; great under lipstick.",
    images: [lip],
    featured: false,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.6,
    review_count: 110,
  },
  {
    id: "lip-hydra-01",
    sku: "AURV-LIP-HYD-01",
    name: "Hydrating Lip Therapy",
    slug: "hydrating-lip-therapy",
    category: "lip",
    brand: "Aurvelia",
    description: "Lightweight lip treatment with long-lasting hydration.",
    price: 449,
    sale_price: null,
    stock: 95,
    ingredients: ["Hyaluronic Acid", "Squalane"],
    benefits: ["Hydration", "Plumping"],
    skin_types: ["All"],
    skin_concerns: ["Thin lips", "Dryness"],
    how_to_use: "Apply morning and night for best results.",
    images: [lip],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.5,
    review_count: 44,
  },
  {
    id: "lip-daily-01",
    sku: "AURV-LIP-DLY-01",
    name: "Daily Lip Protect Balm",
    slug: "daily-lip-protect-balm",
    category: "lip",
    brand: "Aurvelia",
    description: "Everyday protective balm that shields lips and provides lasting moisture.",
    price: 499,
    sale_price: null,
    stock: 110,
    ingredients: ["Beeswax", "Shea Butter", "Vitamin E"],
    benefits: ["Protection", "Long-lasting moisture"],
    skin_types: ["All"],
    skin_concerns: ["Dryness", "Chapping"],
    how_to_use: "Apply liberally throughout the day and before outdoor exposure.",
    images: [lip],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.6,
    review_count: 27,
  },

  // Body (body.jpg)
  {
    id: "body-silk-01",
    sku: "AURV-BDY-SLK-01",
    name: "Body Silk Lotion",
    slug: "body-silk-lotion",
    category: "body",
    brand: "Aurvelia",
    description: "Silk-finish body lotion for smooth, touchable skin.",
    price: 649,
    sale_price: null,
    stock: 60,
    ingredients: ["Squalane", "Sweet Almond Oil"],
    benefits: ["Softness", "Hydration"],
    skin_types: ["All"],
    skin_concerns: ["Dryness"],
    how_to_use: "Massage into damp skin after shower.",
    images: [body],
    featured: true,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.7,
    review_count: 88,
  },
  {
    id: "body-nourish-01",
    sku: "AURV-BDY-NRS-01",
    name: "Nourishing Body Cream",
    slug: "nourishing-body-cream",
    category: "body",
    brand: "Aurvelia",
    description: "Ultra-nourishing cream for dry, thirsty skin.",
    price: 599,
    sale_price: null,
    stock: 70,
    ingredients: ["Shea Butter", "Cocoa Extract"],
    benefits: ["Deep nourishment", "Comfort"],
    skin_types: ["Dry"],
    skin_concerns: ["Very dry skin"],
    how_to_use: "Use nightly on areas needing extra care.",
    images: [body],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.6,
    review_count: 52,
  },
  {
    id: "body-cocoa-01",
    sku: "AURV-BDY-COC-01",
    name: "Cocoa Body Butter",
    slug: "cocoa-body-butter",
    category: "body",
    brand: "Aurvelia",
    description: "Rich cocoa-infused body butter for intensive repair.",
    price: 699,
    sale_price: null,
    stock: 35,
    ingredients: ["Cocoa Butter", "Shea Butter"],
    benefits: ["Intense hydration", "Luxury feel"],
    skin_types: ["Very Dry"],
    skin_concerns: ["Cracked skin"],
    how_to_use: "Apply generously to dry areas.",
    images: [body],
    featured: false,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.8,
    review_count: 46,
  },
  {
    id: "body-daily-01",
    sku: "AURV-BDY-DLY-01",
    name: "Daily Moisture Lotion",
    slug: "daily-moisture-lotion",
    category: "body",
    brand: "Aurvelia",
    description: "Non-greasy daily lotion for everyday softness.",
    price: 499,
    sale_price: null,
    stock: 95,
    ingredients: ["Glycerin", "Aloe Vera"],
    benefits: ["Light hydration", "Fast absorb"],
    skin_types: ["All"],
    skin_concerns: ["Everyday dryness"],
    how_to_use: "Apply after shower to slightly damp skin.",
    images: [body],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.5,
    review_count: 61,
  },
  {
    id: "body-bright-01",
    sku: "AURV-BDY-BRT-01",
    name: "Brightening Body Lotion",
    slug: "brightening-body-lotion",
    category: "body",
    brand: "Aurvelia",
    description: "Light body lotion with subtle brightening botanicals.",
    price: 549,
    sale_price: null,
    stock: 48,
    ingredients: ["Vitamin C", "Niacinamide"],
    benefits: ["Even tone", "Hydration"],
    skin_types: ["All"],
    skin_concerns: ["Dullness"],
    how_to_use: "Use daily on body for improved radiance.",
    images: [body],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.4,
    review_count: 37,
  },
];

export default fallbackProducts;
