import serum from "@/assets/products/serum.jpg";
import cleanser from "@/assets/products/cleanser.jpg";
import moisturizer from "@/assets/products/moisturizer.jpg";
import sunscreen from "@/assets/products/sunscreen.jpg";
import toner from "@/assets/products/toner.jpg";
import mask from "@/assets/products/mask.jpg";
import lip from "@/assets/products/lip.jpg";
import body from "@/assets/products/body.jpg";
import type { Product } from "@/lib/products";

export const fallbackProducts: Product[] = [
  {
    id: "aurv-serum-01",
    sku: "AURV-SRM-01",
    name: "Aurvelia Vitamin C Radiance Serum",
    slug: "vitamin-c-radiance-serum",
    category: "serum",
    brand: "Aurvelia",
    description:
      "A luminous vitamin C serum that boosts radiance, evens skin tone and reduces the appearance of dark spots.",
    price: 3999,
    sale_price: null,
    stock: 25,
    ingredients: ["Ascorbic Acid (Vitamin C)", "Hyaluronic Acid", "Niacinamide"],
    benefits: ["Brightening", "Hydration", "Even tone"],
    skin_types: ["Normal", "Dry", "Combination"],
    skin_concerns: ["Dullness", "Pigmentation"],
    how_to_use: "Apply 2-3 drops to cleansed skin each morning before moisturizer and sunscreen.",
    images: [serum],
    featured: true,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.7,
    review_count: 124,
  },
  {
    id: "aurv-cleanser-01",
    sku: "AURV-CLN-01",
    name: "Aurvelia Gentle Radiance Cleanser",
    slug: "gentle-radiance-cleanser",
    category: "cleanser",
    brand: "Aurvelia",
    description:
      "A silky cleanser that removes impurities while preserving the skin's natural moisture barrier.",
    price: 2499,
    sale_price: 1999,
    stock: 40,
    ingredients: ["Squalane", "Glycerin", "Panthenol"],
    benefits: ["Cleansing", "Soothing", "Hydrating"],
    skin_types: ["All"],
    skin_concerns: ["Sensitivity", "Dryness"],
    how_to_use: "Massage into damp skin and rinse. Use morning and evening.",
    images: [cleanser],
    featured: false,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.6,
    review_count: 86,
  },
  {
    id: "aurv-moist-01",
    sku: "AURV-MST-01",
    name: "Aurvelia Hydrating Day Moisturizer",
    slug: "hydrating-day-moisturizer",
    category: "moisturizer",
    brand: "Aurvelia",
    description:
      "Lightweight yet deeply nourishing moisturizer with long-lasting hydration and a satin finish.",
    price: 3299,
    sale_price: null,
    stock: 30,
    ingredients: ["Ceramides", "Squalane", "Glycerin"],
    benefits: ["Hydration", "Barrier repair", "Comfort"],
    skin_types: ["Normal", "Dry", "Combination"],
    skin_concerns: ["Dehydration", "Sensitivity"],
    how_to_use: "Apply morning and evening on clean skin. Layer under sunscreen in the day.",
    images: [moisturizer],
    featured: true,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.8,
    review_count: 210,
  },
  {
    id: "aurv-sspf-01",
    sku: "AURV-SPF-01",
    name: "Aurvelia Mineral Shield SPF 50",
    slug: "mineral-shield-spf-50",
    category: "sunscreen",
    brand: "Aurvelia",
    description:
      "A weightless mineral sunscreen that provides broad-spectrum protection with a soft, non-greasy finish.",
    price: 2899,
    sale_price: null,
    stock: 18,
    ingredients: ["Zinc Oxide", "Titanium Dioxide", "Vitamin E"],
    benefits: ["UV protection", "Antioxidant"],
    skin_types: ["All"],
    skin_concerns: ["UV protection"],
    how_to_use: "Apply generously 15 minutes before sun exposure. Reapply every 2 hours.",
    images: [sunscreen],
    featured: false,
    best_seller: true,
    new_arrival: false,
    is_active: true,
    rating: 4.5,
    review_count: 64,
  },
  {
    id: "aurv-toner-01",
    sku: "AURV-TNR-01",
    name: "Aurvelia Balancing Toner",
    slug: "balancing-toner",
    category: "toner",
    brand: "Aurvelia",
    description:
      "A gentle pH-balancing toner that refreshes skin and enhances absorption of serums.",
    price: 1999,
    sale_price: null,
    stock: 50,
    ingredients: ["Lactic Acid", "Aloe Vera", "Hyaluronic Acid"],
    benefits: ["Exfoliation", "Hydration", "Tone refinement"],
    skin_types: ["All"],
    skin_concerns: ["Texture", "Dryness"],
    how_to_use: "Apply to a cotton pad and sweep over cleansed skin, or pat in with hands.",
    images: [toner],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.4,
    review_count: 42,
  },
  {
    id: "aurv-mask-01",
    sku: "AURV-MSK-01",
    name: "Aurvelia Restorative Clay Mask",
    slug: "restorative-clay-mask",
    category: "mask",
    brand: "Aurvelia",
    description:
      "A calming clay mask to deeply cleanse pores and rejuvenate dull-looking skin.",
    price: 2499,
    sale_price: 2199,
    stock: 20,
    ingredients: ["Kaolin", "Charcoal", "Aloe"],
    benefits: ["Deep clean", "Refinement", "Glow"],
    skin_types: ["Oily", "Combination"],
    skin_concerns: ["Clogged pores", "Dullness"],
    how_to_use: "Apply a thin layer to clean skin for 10–12 minutes, then rinse thoroughly.",
    images: [mask],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.3,
    review_count: 28,
  },
  {
    id: "aurv-lip-01",
    sku: "AURV-LIP-01",
    name: "Aurvelia Nourishing Lip Treatment",
    slug: "nourishing-lip-treatment",
    category: "lip",
    brand: "Aurvelia",
    description:
      "A rich lip treatment to restore softness and protect against dryness.",
    price: 999,
    sale_price: null,
    stock: 75,
    ingredients: ["Shea Butter", "Squalane", "Vitamin E"],
    benefits: ["Repair", "Moisture"],
    skin_types: ["All"],
    skin_concerns: ["Dryness"],
    how_to_use: "Apply as needed to lips and cuticles.",
    images: [lip],
    featured: false,
    best_seller: false,
    new_arrival: true,
    is_active: true,
    rating: 4.6,
    review_count: 19,
  },
  {
    id: "aurv-body-01",
    sku: "AURV-BDY-01",
    name: "Aurvelia Silk Body Elixir",
    slug: "silk-body-elixir",
    category: "body",
    brand: "Aurvelia",
    description:
      "A lightweight body elixir that leaves skin satin-smooth and subtly fragranced.",
    price: 2199,
    sale_price: null,
    stock: 40,
    ingredients: ["Squalane", "Jojoba Oil", "Vitamin E"],
    benefits: ["Hydration", "Softness"],
    skin_types: ["All"],
    skin_concerns: ["Dryness"],
    how_to_use: "Massage onto body after shower while skin is damp.",
    images: [body],
    featured: false,
    best_seller: false,
    new_arrival: false,
    is_active: true,
    rating: 4.5,
    review_count: 33,
  },
];

export default fallbackProducts;
